global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'All'
    scrape_interval: 15s
    scrape_timeout: 15s 
    static_configs:
      - targets: ['111.222.123.136:9100']        
      - targets: ['check.mung.kr:80']        

  - job_name: 'nodeexporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'mysqld-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['mysqld-exporter:9104']      

  - job_name: 'nginx-prometheus-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']

  # - job_name: 'pushgateway'
  #   scrape_interval: 15s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['pushgateway:9091']
  
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

